export const rpcUrls: Record<string, string[]> = {
    ethereum: ["https://rpc.ankr.com/eth"],
    sepolia: ["https://rpc.ankr.com/eth_sepolia"],
    avalanche: ["https://avalanche-c-chain-rpc.publicnode.com", "https://rpc.ankr.com/avalanche"],
    avalancheFuji: ["https://avalanche-fuji-c-chain-rpc.publicnode.com"],
    arbitrum: [
        "https://arbitrum-one-rpc.publicnode.com",
        "https://arbitrum.meowrpc.com",
        "https://arbitrum.gateway.tenderly.co",
        "https://1rpc.io/arb",
        "https://arbitrum.public.blockpi.network/v1/rpc/public",
        "https://arbitrum.drpc.org",
        "https://arbitrum-one-rpc.publicnode.com",
        "https://public-arb-mainnet.fastnode.io",
        "https://arb1.lava.build",
        "https://rpc.sentio.xyz/arbitrum-one",
        "https://arb1.arbitrum.io/rpc",
        "https://arbitrum-one-public.nodies.app",
        "https://arbitrum.rpc.subquery.network/public",
        "https://arbitrum-one.public.blastapi.io",
        "https://arb-one.api.pocket.network",
        "https://arbitrum.api.onfinality.io/public",
    ],
    arbitrumSepolia: ["https://arbitrum-sepolia-rpc.publicnode.com"],
    optimism: [
        "https://gateway.tenderly.co/public/optimism",
        "https://go.getblock.io/e8a75f8dcf614861becfbcb185be6eb4",
        "https://1rpc.io/op",
        "https://api-optimism-mainnet-archive.n.dwellir.com/2ccf18bf-2916-4198-8856-42172854353c",
        "https://optimism-public.nodies.app",
        "https://mainnet.optimism.io",
        "https://optimism-rpc.publicnode.com",
        "https://public-op-mainnet.fastnode.io",
        "https://optimism.public.blockpi.network/v1/rpc/public",
        "https://optimism-mainnet.gateway.tatum.io",
        "https://optimism.gateway.tenderly.co",
        "https://optimism.drpc.org",
        "https://rpc.sentio.xyz/optimism",
        "https://optimism.meowrpc.com",
        "https://optimism.api.onfinality.io/public",
        "https://optimism.rpc.subquery.network/public",
        "https://optimism-rpc.publicnode.com",
    ],
    optimismSepolia: ["https://rpc.ankr.com/optimism_sepolia"],
    polygon: ["https://polygon-bor-rpc.publicnode.com", "https://polygon-rpc.com", "https://rpc.ankr.com/polygon"],
    polygonAmoy: ["https://polygon-amoy-bor-rpc.publicnode.com"],
    base: [
        "https://base.drpc.org",
        `https://base-rpc.publicnode.com`,
        "https://gateway.tenderly.co/public/base",
        "https://base-rpc.publicnode.com",
        "https://base.meowrpc.com",
        "https://base.rpc.subquery.network/public",
        "https://base.public.blockpi.network/v1/rpc/public",
        "https://base-public.nodies.app",
        "https://base.gateway.tenderly.co",
        "https://base-mainnet.public.blastapi.io",
        "https://base.lava.build",
        "https://base.llamarpc.com",
        "https://base.rpc.grove.city/v1/01fdb492",
        "https://rpc.ankr.com/base",
    ],
    baseSepolia: ["https://base-sepolia-rpc.publicnode.com"],
    bsc: ["https://rpc.ankr.com/bsc"],
    scroll: ["https://rpc.ankr.com/scroll"],
    scrollSepolia: ["https://rpc.ankr.com/scroll_sepolia"],
}
