export const rpcUrls: Record<string, string[]> = {
    ethereum: ["https://rpc.ankr.com/eth"],
    sepolia: ["https://rpc.ankr.com/eth_sepolia"],
    avalanche: ["https://avalanche-c-chain-rpc.publicnode.com"],
    avalancheFuji: ["https://avalanche-fuji-c-chain-rpc.publicnode.com"],
    arbitrum: ["https://arbitrum-one-rpc.publicnode.com", "https://rpc.ankr.com/arbitrum"],
    arbitrumSepolia: ["https://arbitrum-sepolia-rpc.publicnode.com"],
    optimism: ["https://optimism-rpc.publicnode.com", "https://rpc.ankr.com/optimism"],
    optimismSepolia: ["https://rpc.ankr.com/optimism_sepolia"],
    polygon: ["https://polygon-bor-rpc.publicnode.com", "https://rpc.ankr.com/polygon"],
    polygonAmoy: ["https://polygon-amoy-bor-rpc.publicnode.com"],
    base: [`https://base-rpc.publicnode.com`, "https://rpc.ankr.com/base"],
    baseSepolia: ["https://base-sepolia-rpc.publicnode.com"],
    bsc: ["https://rpc.ankr.com/bsc"],
    scroll: ["https://rpc.ankr.com/scroll"],
    scrollSepolia: ["https://rpc.ankr.com/scroll_sepolia"],
}
